FROM centos:7

RUN yum -y install epel-release
RUN yum -y update

RUN yum -y install python-pip

RUN pip install aem-cmd

RUN mkdir -p /usr/local/aem-cmd
WORKDIR /usr/local/aem-cmd

COPY verify-installation.sh .
COPY expected_output .

ENTRYPOINT "./verify-installation.sh"
